# Generated by Django 3.1.4 on 2021-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='retention',
            field=models.CharField(choices=[('Always Available', 'Always Available'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
    ]
