# Generated by Django 3.1.4 on 2021-04-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_auto_20210408_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='retention',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Always Available', 'Always Available')], default='Inactive', max_length=20),
        ),
    ]
