# Generated by Django 3.1.4 on 2021-04-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_auto_20210408_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='retention',
            field=models.CharField(choices=[('Always Available', 'Always Available'), ('Inactive', 'Inactive')], default='Always Available', max_length=20),
        ),
    ]
