# Generated by Django 3.1.4 on 2021-04-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0008_auto_20210409_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(blank=True, max_length=220)),
                ('file_id', models.CharField(default='NA', max_length=220)),
                ('folder_id', models.CharField(blank=True, max_length=220)),
                ('document_id', models.CharField(blank=True, max_length=220, null=True)),
                ('approver', models.CharField(blank=True, max_length=220, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='folder',
            name='retention',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Always Available', 'Always Available')], default='Inactive', max_length=20),
        ),
    ]
