# Generated by Django 3.1.4 on 2021-04-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_auto_20210409_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='approver',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
