# Generated by Django 3.1.4 on 2021-04-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0011_auto_20210409_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='country',
            field=models.CharField(default='Nigeria', max_length=25),
            preserve_default=False,
        ),
    ]
