# Generated by Django 3.1.4 on 2021-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0012_department_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='upload_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
