# Generated by Django 3.1.4 on 2021-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0013_auto_20210416_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='file_id',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
