# Generated by Django 3.1.4 on 2021-04-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0015_usermanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'groupmanagement',
            },
        ),
        migrations.DeleteModel(
            name='UserManagement',
        ),
    ]
