# Generated by Django 3.1.4 on 2021-04-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0016_auto_20210417_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmanagement',
            old_name='group',
            new_name='group_name',
        ),
    ]
