# Generated by Django 3.1.4 on 2021-04-17 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0017_auto_20210417_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmanagement',
            name='entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupmanagement',
            name='update_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
