# Generated by Django 3.1.4 on 2021-04-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0018_auto_20210417_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmanagement',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
    ]
