# Generated by Django 3.1.4 on 2021-04-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0022_auto_20210418_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='group_name',
            field=models.CharField(default='none', max_length=125),
            preserve_default=False,
        ),
    ]
