# Generated by Django 3.1.4 on 2021-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0024_addusergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='group_name',
            field=models.CharField(default='none', max_length=125),
            preserve_default=False,
        ),
    ]
