# Generated by Django 3.2.9 on 2021-11-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0027_adduserdept'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='author',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
