# Generated by Django 3.2.9 on 2021-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0028_department_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUserFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=120)),
                ('entry_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='approvals',
            name='author',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='filetype',
            name='author',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='folder',
            name='author',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='versionupload',
            name='author',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
