# Generated by Django 3.2.9 on 2021-11-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0029_auto_20211121_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduserfolder',
            name='department_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
