# Generated by Django 3.2.9 on 2021-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0030_adduserfolder_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduserdept',
            name='dept_access',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
