# Generated by Django 3.2.9 on 2021-11-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0032_alter_adduserdept_dept_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduserfolder',
            name='folder_access',
            field=models.CharField(default='full', max_length=5),
        ),
    ]
