# Generated by Django 3.2.9 on 2021-12-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0035_auto_20211205_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='folder',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
