# Generated by Django 3.2.9 on 2021-12-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0036_auto_20211205_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
