# Generated by Django 3.2.9 on 2021-12-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0039_alter_department_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=220)),
                ('new_upload', models.FileField(upload_to='')),
                ('department_id', models.CharField(blank=True, max_length=220)),
                ('file_id', models.CharField(default='NA', max_length=220)),
                ('folder_id', models.CharField(blank=True, max_length=220)),
                ('document_id', models.CharField(blank=True, max_length=220, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
